<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.9.0 setup script by Michal Cihar <michal@cihar.com>
 * Version: $Id: setup.php,v 1.36.2.3 2006/08/22 20:13:54 lem9 Exp $
 * Date: Fri, 22 Sep 2006 19:40:02 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (config:cseschol) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'cseschol';
$cfg['Servers'][$i]['password'] = 'JAwNuTrJ';
$cfg['Servers'][$i]['only_db'] = 'csescholars';

/* End of servers configuration */

?>
